version: "3"
services:
  frontend:
    container_name: goserver
    image: goweb:v1
    ports:
      - "8001:8001"
    environment:
      - GOLANG_IP=182.18.7.9
      - GOLANG_PORT=8001
      - NODEJS_IP=182.18.7.7
      - NODEJS_PORT=3001
    volumes:
      - ./Go:/App/
    networks:
      testing_net:
            ipv4_address: 182.18.7.9
    depends_on:
      - backend
  backend:
    container_name: nodeserver
    image: nodeweb:v1
    ports:
      - "3001:3001"
    environment:
      - NODEJS_IP=182.18.7.7
      - NODEJS_PORT=3001
    volumes:
      - ./Node:/App/
      - /App/node_modules
    networks:
      testing_net:
            ipv4_address: 182.18.7.7

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 182.18.7.0/24